# Numpy

In [2]:
import numpy as np

In [15]:
a = np.array([1, 2, 3]) # array adalah bentuk list yang dapat di operasikan secara matematika

In [4]:
a * 3

array([3, 6, 9])

# Fungsi Matematika

In [5]:
np.sum(a)

6

In [6]:
np.mean(a)

2.0

In [7]:
np.std(a)

0.816496580927726

In [8]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [9]:
np.arange(5) # mirip dengan range yang ada di looping list tadi 

array([0, 1, 2, 3, 4])

In [14]:
np.linspace(1, 5, 5) # maksudnya dari range 1 - 5 di pecah mejadi 5 bagian sehingga keluarlah output seperti di bawah (inclusive semua)

array([1., 2., 3., 4., 5.])

In [16]:
np.logspace(1, 5, 5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

# Random

In [8]:
 np.random.rand(10, 2)

array([[0.19680743, 0.57764759],
       [0.13759508, 0.47316963],
       [0.811904  , 0.67770232],
       [0.55209474, 0.11202276],
       [0.53921122, 0.72692216],
       [0.41587667, 0.76003268],
       [0.06506782, 0.05400244],
       [0.25085722, 0.33749287],
       [0.59401135, 0.13403832],
       [0.38092945, 0.85156469]])

# Controlled Randomness

In [9]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])